baseURL: "https://bartlomiejmika.com/"
title: Bartlomiej Mika
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-172742383-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Bartlomiej Mika
  description: "Personal blog, opinions are my own"
  keywords: [Blog, Golang, DevOps, Python]
  author: Bartlomiej Mika
  # author: ["Me", "You"] # multiple authors
  images: ["img/bartlomiej_mika.jpeg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "img/favicon.ico"
    favicon16x16: "img/favicon.ico"
    favicon32x32: "img/favicon.ico"
    apple_touch_icon: "img/favicon.ico"
    safari_pinned_tab: "img/favicon.ico"

  label:
    text: "Bartlomiej Mika"
    icon: img/bartlomiej_mika.jpeg
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Bartlomiej Mika
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there, I'm Bart \U0001F44B"
    Content: I am <strong>Golang Developer</strong> with a passion for building cool stuff.

  socialIcons:
    - name: email
      url: "mailto:bart@mikasoftware.com"
    - name: linkedin
      url: "https://ca.linkedin.com/in/bartlomiej-mika-a9a5683b"
    - name: github
      url: "https://github.com/bartmika"
    - name: reddit
      url: "https://www.reddit.com/user/eurasiasoft"

  analytics:
    google:
      SiteVerificationTag: "UA-172742383-1"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/bartmika/bartlomiejmika-hugo/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
